# Generated by Django 3.1.5 on 2021-08-30 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_factor_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='customize_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.factor_tb')),
                ('hobby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.hobby_tb')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.register_tb')),
            ],
        ),
    ]
