# Generated by Django 3.1.5 on 2021-08-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_customize_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='agefactor_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField(max_length=20)),
                ('max_age', models.IntegerField(max_length=20)),
                ('factor_name', models.CharField(max_length=20)),
            ],
        ),
    ]
