# Generated by Django 3.1.5 on 2021-08-31 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_season_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='seasonfactor_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_name', models.CharField(max_length=20)),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.season_tb')),
            ],
        ),
    ]
