# Generated by Django 3.1.5 on 2021-08-31 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_seasonfactor_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='countryfactor_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(max_length=20)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.country_tb')),
                ('factor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.seasonfactor_tb')),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.season_tb')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.state_tb')),
            ],
        ),
    ]
