# Generated by Django 2.1.7 on 2021-08-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_countryfactor_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agefactor_tb',
            name='max_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='agefactor_tb',
            name='min_age',
            field=models.IntegerField(),
        ),
    ]
