# Generated by Django 2.1.7 on 2021-08-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_auto_20210824_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryfactor_tb',
            name='month',
            field=models.IntegerField(),
        ),
    ]
