# Generated by Django 3.1.7 on 2021-07-05 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0002_hobby_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='hobbies_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.hobby_tb')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.register_tb')),
            ],
        ),
    ]
