# Generated by Django 3.1.5 on 2021-08-31 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_agefactor_tb'),
        ('User', '0002_message_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='agecustomize_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.factor_tb')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.register_tb')),
            ],
        ),
    ]
