# Generated by Django 2.1.7 on 2021-08-23 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_countryfactor_tb'),
        ('User', '0003_agecustomize_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='customizecountryfactor_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.factor_tb')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.register_tb')),
            ],
        ),
    ]
