# Generated by Django 2.1.7 on 2021-08-24 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_customizecountryfactor_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizecountryfactor_tb',
            name='factor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.seasonfactor_tb'),
        ),
    ]
