# Generated by Django 2.1.7 on 2021-08-24 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_auto_20210824_0517'),
        ('User', '0005_auto_20210824_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_id', to='Admin.register_tb')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='Admin.register_tb')),
            ],
        ),
    ]
