# Generated by Django 2.1.7 on 2021-08-24 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_auto_20210824_0517'),
        ('User', '0007_blacklist_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='trash_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.message_tb')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.register_tb')),
            ],
        ),
    ]
