# Generated by Django 2.1.7 on 2021-08-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_message_tb_filter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_tb',
            name='filter_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
