# Generated by Django 2.1.7 on 2021-08-24 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20210824_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agecustomize_tb',
            name='factor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.agefactor_tb'),
        ),
    ]
